model_type: "gpt2-xl"
tokenizer_path: "gpt2"
num_layers_unfrozen: 0.67

train_args:
  output_dir: "temp/gpt2xl-rm"
  num_train_epochs: 1
  logging_steps: 100
  save_strategy: "epoch"
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 1.0e-5
  save_total_limit: 1
  logging_dir: "./logs"
  fp16: False
  bf16: True

data_path: "AlekseyKorshuk/cup-it-ds-ranked-test"
trainer_type: "ranked"
order: [ "0", "1", "2", "3", "4" ]