model_path: "gpt2"
model_type: "causal"
tokenizer_path: "gpt2"
num_layers_unfrozen: 0.75

train_args:
  output_dir: "/tmp/gpt2-test"
  num_train_epochs: 1
  logging_steps: 100
  eval_steps: 10
  evaluation_strategy: "steps"
  save_strategy: "epoch"
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 1.0e-5
  save_total_limit: 1
  logging_dir: "./logs"
  fp16: True
  bf16: False

data_path: "AlekseyKorshuk/cup-it-ds-ranked-small"
trainer_type: "ranked"
order: [ "0", "1", "2", "3", "4" ]