model_path: "EleutherAI/gpt-neox-20b"
model_type: "causal"
tokenizer_path: "EleutherAI/gpt-neox-20b"
num_layers_unfrozen: 0.5

train_args:
  output_dir: "/fsx/alex/ckpts/gptneox-rm"
  num_train_epochs: 1
  logging_steps: 100
  save_strategy: "epoch"
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  warmup_steps: 100
  weight_decay: 0.01
  learning_rate: 1.0e-5
  logging_dir: "./logs"
  fp16: True
  bf16: False

data_path: "Dahoas/rm-static"
trainer_type: "sparse"